#!/bin/bash
# RClone Config file
RCLONE_CONFIG=/root/.config/rclone/rclone.conf
export RCLONE_CONFIG

#exit if running
if [[ "`pidof -x $(basename $0) -o %PPID`" ]]; then
        echo "This script is already running with PID `pidof -x $(basename $0) -o %PPID`"
        exit; fi

# Move older local files to the cloud
/usr/bin/rclone move /local/ gcrypt0:/ --log-file /opt/rclone/logs/upload0.log -v --exclude-from /opt/rclone/scripts/excludes --delete-empty-src-dirs --user-agent root --fast-list --max-transfer 700G
rm /opt/rclone/scripts/upcount
echo "1" >> /opt/rclone/scripts/upcount
